[build]
  command = "cd dashboard && npm install && npm run build"
  publish = "dashboard/out"
  base = "."

[env]
  NEXT_PUBLIC_BACKEND_URL = "https://queztl-core-backend.onrender.com"
  NEXT_PUBLIC_API_KEY = "b8f3d9e7a6c5f1d2e4a9b7c6d8f3e1a2b4c7d9e6f8a1c3d5e7f9a2b4c6d8e1f3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
